### ISSUE TITLE
Wrapped TODO

### ISSUE THREAD

**Issue by therungg** [therungg/therun-frontend#294]
# Wrapped TODO

Wrapped is going great. To keep overview, here's what we want to add/change:

## Bugs

- [x] Game art sometimes doesn't load when we definitely have that game and its art. @therungg fix
- [x] The scrolling behavior is completely broken
- [x] scroll snap with gsap ScrollTriggers is super duper clunky on mobile
- [x] @florence-wolfe calendar heatmap is mounting (but not displaying anything) on small devices and throwing console errors.
- [x] races images are way too small. Game images for ants
- [x] pagination buttons should **not** exist on mobile devices
- [x] @florence-wolfe all sections that display Top 3 of anything or any numbered slice should use the list length for the display value instead of 3.

## Styling

- [ ] Add the cool page styling to the loading page and the timezone-set-page.
- [x] The other pages could use some color as well. It's too big a contrast when the rest is just black.
- [x] The other pages have color now, which is great. However, the intro page lost a lot of color and background quality. We should fix that
- [x] Pagination buttons should be a bit more to the left, and the pagination display more to the right. That way, it will never be in the way of the content.
- [x] When we do the snap to scroll, I feel every "page" needs a title.
- [x] Maybe we need to show somewhere on which section you are, and what the next one is. Also maybe subtle buttons to navigate them?
  - [x] somewhat done — we have page numbers and pagination buttons but we could possibly replace both with a vertical progress stepper
- [ ] Need more images, like the bunny appearing on random spots or something. Maybe rank people with different colors of bunny
- [x] I would prefer the section body always being centered vertically. Right now it's just mb-5 below the section title.

## First page (intro)

- [x] Looks great, I think I want different text. Needs to be catchier. @therungg will fix this

## Second page (main stats)

- [x] In general I feel like the second page with stats could show a bit more. It's bare now: 
- Absolutely needed: Stat for total playtime. Should be very prominent on this page.
- Absolutely needed: Total times the user split
- Absolutely needed: Amount of PB's gotten
- Could be cool: Playtime per month in a graph?
- Roast? Reset count and percentage, 
- Roast? Reset count on first split, time spent resetting on first split

## Third page (streak)

- [x] For the daily streak section, show the dates where the streak was achieved. 
- [x] Add some cool styling to the stat items. It's a bit bland now
- [x] Show the finished runs and PB's during the streak.

## Fourth page (favorite games)

- [x] Maybe show therun's logo when a game image is missing
- [x] We could add more stats for the game. How many runs done/finished per game. Which categories were run, and how much. What was the PB before and after the year. Same for SOB.
- [x] We could show the other games too seperately, but not highlighted, but maybe in some scrollbox or something.

## Things we should add on seperate pages

- [x] Add the activity graph somewhere. Can be used directly the same as the Activity tab. Data is the same.
- [x] Whole page dedicated to PB's and finished runs? We can show a lot:
- Heatmap of finished runs and heatmap of PB's, like the github activity thing,
- Show PB before the year and after the year, and the improvements
- Show how much SOB has improved
- [x] Download image of overview
- [x] Page for Race data
- [ ] A roast page
- [x] Final page should maybe be a final overview anyway?
- [x] At the end I'd like a page to thank people for their support, and to let them know they can subscribe on patron if they want a wrapped next year as well
